TKNECO-25: Import maven Task
openshift-pipelines/task-maven pull request #1
Opened 2023-10-30 14:51 UTC by Aneesh-M-Bhat

Story: https://issues.redhat.com/browse/TKNECO-25

WIP PR
Currently, the mvn task is working as intended.
The pipeline used for test is also working correctly.

ToDo: cleanup & refactoring

To check it out, use `make install` to install task or `make test-e2e` to run the tests

2023-10-30 14:54 UTC, Aneesh-M-Bhat commented
@otaviof @vdemeester PTAL

2023-11-08 09:00 UTC, otaviof requested changes
Very good progress, thanks! On my initial pass we have a number of things to address as well.

2023-11-13 11:42 UTC, Aneesh-M-Bhat commented on templates/task-mvn.yaml
> +      default: {{ .Values.images.mvn }}
I'll remove this param for the 1st implementation, since that makes more sense, lets discuss whether we need to add it later on.

2023-11-15 09:43 UTC, Aneesh-M-Bhat commented on scripts/mvn-generate.sh
> +fi
Made an issue for it, will look into it asap.

2023-11-15 09:44 UTC, Aneesh-M-Bhat commented on templates/task-mvn.yaml
> +  workspaces:
Made an issue for it, will look into it asap.

2023-11-15 09:44 UTC, Aneesh-M-Bhat commented on templates/task-mvn.yaml
> +      default: ""
tracked in a issue.

2023-11-15 09:44 UTC, Aneesh-M-Bhat commented on templates/task-mvn.yaml
> +      default: ""
tracked in the secrets issue.

2023-11-15 09:45 UTC, Aneesh-M-Bhat commented on templates/task-mvn.yaml
> +      default: "http"
tracked in the proxy issue.

2023-11-15 12:15 UTC, Aneesh-M-Bhat commented on templates/task-mvn.yaml
> +        runAsUser: 65532
I believe both of these steps need to run as same user, otherwise it causes an issue and hence im keeping it atm.

2023-11-15 12:16 UTC, Aneesh-M-Bhat commented on templates/task-mvn.yaml
> +        runAsUser: 65532
I believe both of these steps need to run as same user, otherwise it causes an issue and hence im keeping it atm.

2023-11-21 12:15 UTC, vdemeester approved these changes
Let's merge this and iterate over it.

2023-11-21 12:15 UTC, merged